import Foundation

/// Baked at build time so an install is verifiable on-device (More > About).
/// Regenerated by the build wrapper before each xcodebuild.
enum BuildStamp {
  static let commit = "aa07dbb"
  static let commitCount = 51
  static let builtAt = "2026-06-22 00:35"

  static var summary: String {
    "#\(commitCount) · \(commit) · \(builtAt)"
  }
}
