import Foundation

/// Baked at build time so an install is verifiable on-device (More > About).
/// Regenerated by the build wrapper before each xcodebuild.
enum BuildStamp {
  static let commit = "07a8773"
  static let commitCount = 44
  static let builtAt = "2026-06-21 22:20"

  static var summary: String {
    "#\(commitCount) · \(commit) · \(builtAt)"
  }
}
