import Foundation

/// Baked at build time so an install is verifiable on-device (More > About).
/// Regenerated by the build wrapper before each xcodebuild.
enum BuildStamp {
  static let commit = "0afb294"
  static let commitCount = 46
  static let builtAt = "2026-06-21 22:54"

  static var summary: String {
    "#\(commitCount) · \(commit) · \(builtAt)"
  }
}
