name: iOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Package IPA
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust iOS targets
        run: rustup target add aarch64-apple-ios x86_64-apple-ios aarch64-apple-ios-sim

      - name: Build Application and Package IPA
        run: |
          xcodebuild clean build \
            -project GooseSwift.xcodeproj \
            -scheme GooseSwift \
            -destination "generic/platform=iOS" \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            CONFIGURATION_BUILD_DIR="$(pwd)/build"
            
          cd build
          mkdir Payload
          cp -R GooseSwift.app Payload/
          zip -r Whoof.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Whoof-IPA
          path: build/Whoof.ipa
